services:
  db:
    image: postgres:latest
    container_name: django_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default_network

  redis:
    image: redis:latest
    container_name: django_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default_network

#  celery_worker:
#    build: .
#    container_name: celery_worker
#    command: celery -A core worker --loglevel=info
#    depends_on:
#      - redis
#      - db
#    volumes:
#      - .:/usr/src/app
#    networks:
#      - default_network
#
#  celery_beat:
#    build: .
#    container_name: celery_beat
#    command: celery -A core beat --loglevel=info
#    depends_on:
#      - redis
#      - db
#    volumes:
#      - .:/usr/src/app
#    networks:
#      - default_network

networks:
  default_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24

volumes:
  postgres_data:
  redis_data: